package freertos

import _ "unsafe"

const EFUSE_WRITE_OP_CODE = 0x5a5a
const EFUSE_READ_OP_CODE = 0x5aa5
const EFUSE_PKG_VERSION_ESP32S3 = 0
const EFUSE_PKG_VERSION_ESP32S3PICO = 1
const EFUSE_SPI_PAD_CONF_1 = 0xFFFFFFFF
const EFUSE_SPI_PAD_CONF_1_V = 0xFFFFFFFF
const EFUSE_SPI_PAD_CONF_1_S = 0
const EFUSE_SPI_PAD_CONF_2 = 0x0003FFFF
const EFUSE_SPI_PAD_CONF_2_V = 0x3FFFF
const EFUSE_SPI_PAD_CONF_2_S = 0
