package freertos

import _ "unsafe"

const GDMA_LL_CHANNEL_MAX_PRIORITY = 5
const GDMA_LL_L2FIFO_BASE_SIZE = 16
const GDMA_LL_EXT_MEM_BK_SIZE_16B = 0
const GDMA_LL_EXT_MEM_BK_SIZE_32B = 1
const GDMA_LL_EXT_MEM_BK_SIZE_64B = 2
const GDMA_LL_AHB_GROUP_START_ID = 0
const GDMA_LL_AHB_NUM_GROUPS = 1
const GDMA_LL_AHB_PAIRS_PER_GROUP = 5
const GDMA_LL_AHB_DESC_ALIGNMENT = 4
const GDMA_LL_AHB_BURST_SIZE_ADJUSTABLE = 1
const GDMA_LL_AHB_RX_BURST_NEEDS_ALIGNMENT = 1
