package freertos

import _ "unsafe"

const SHA256_BLOCK_SZ = 64
const SHA256_DIGEST_SZ = 32
const HMAC_LL_EFUSE_KEY_PURPOSE_DOWN_JTAG = 6
const HMAC_LL_EFUSE_KEY_PURPOSE_DOWN_DIGITAL_SIGNATURE = 7
const HMAC_LL_EFUSE_KEY_PURPOSE_UP = 8
const HMAC_LL_EFUSE_KEY_PURPOSE_DOWN_ALL = 5
