package freertos

import _ "unsafe"

const MWDT_LL_DEFAULT_CLK_PRESCALER = 40000
const MWDT_LL_WKEY_VALUE = 0x50D83AA1
const MWDT_LL_STG_SEL_OFF = 0
const MWDT_LL_STG_SEL_INT = 1
const MWDT_LL_STG_SEL_RESET_CPU = 2
const MWDT_LL_STG_SEL_RESET_SYSTEM = 3
const MWDT_LL_RESET_LENGTH_100_NS = 0
const MWDT_LL_RESET_LENGTH_200_NS = 1
const MWDT_LL_RESET_LENGTH_300_NS = 2
const MWDT_LL_RESET_LENGTH_400_NS = 3
const MWDT_LL_RESET_LENGTH_500_NS = 4
const MWDT_LL_RESET_LENGTH_800_NS = 5
const MWDT_LL_RESET_LENGTH_1600_NS = 6
const MWDT_LL_RESET_LENGTH_3200_NS = 7
