package freertos

import _ "unsafe"

const PANIC_RSN_NONE = 0
const PANIC_RSN_DEBUGEXCEPTION = 1
const PANIC_RSN_DOUBLEEXCEPTION = 2
const PANIC_RSN_KERNELEXCEPTION = 3
const PANIC_RSN_COPROCEXCEPTION = 4
const PANIC_RSN_INTWDT_CPU0 = 5
const PANIC_RSN_INTWDT_CPU1 = 6
const PANIC_RSN_CACHEERR = 7
const PANIC_RSN_MAX = 7
