package freertos

import _ "unsafe"

const I2C_SAR_ADC = 0x69
const I2C_SAR_ADC_HOSTID = 1
const ADC_SAR1_ENCAL_GND_ADDR = 0x7
const ADC_SAR1_ENCAL_GND_ADDR_MSB = 5
const ADC_SAR1_ENCAL_GND_ADDR_LSB = 5
const ADC_SAR2_ENCAL_GND_ADDR = 0x7
const ADC_SAR2_ENCAL_GND_ADDR_MSB = 7
const ADC_SAR2_ENCAL_GND_ADDR_LSB = 7
const ADC_SAR1_INITIAL_CODE_HIGH_ADDR = 0x1
const ADC_SAR1_INITIAL_CODE_HIGH_ADDR_MSB = 0x3
const ADC_SAR1_INITIAL_CODE_HIGH_ADDR_LSB = 0x0
const ADC_SAR1_INITIAL_CODE_LOW_ADDR = 0x0
const ADC_SAR1_INITIAL_CODE_LOW_ADDR_MSB = 0x7
const ADC_SAR1_INITIAL_CODE_LOW_ADDR_LSB = 0x0
const ADC_SAR2_INITIAL_CODE_HIGH_ADDR = 0x4
const ADC_SAR2_INITIAL_CODE_HIGH_ADDR_MSB = 0x3
const ADC_SAR2_INITIAL_CODE_HIGH_ADDR_LSB = 0x0
const ADC_SAR2_INITIAL_CODE_LOW_ADDR = 0x3
const ADC_SAR2_INITIAL_CODE_LOW_ADDR_MSB = 0x7
const ADC_SAR2_INITIAL_CODE_LOW_ADDR_LSB = 0x0
const ADC_SAR1_DREF_ADDR = 0x2
const ADC_SAR1_DREF_ADDR_MSB = 0x6
const ADC_SAR1_DREF_ADDR_LSB = 0x4
const ADC_SAR2_DREF_ADDR = 0x5
const ADC_SAR2_DREF_ADDR_MSB = 0x6
const ADC_SAR2_DREF_ADDR_LSB = 0x4
const ADC_SAR1_SAMPLE_CYCLE_ADDR = 0x2
const ADC_SAR1_SAMPLE_CYCLE_ADDR_MSB = 0x2
const ADC_SAR1_SAMPLE_CYCLE_ADDR_LSB = 0x0
const ADC_SARADC_DTEST_RTC_ADDR = 0x7
const ADC_SARADC_DTEST_RTC_ADDR_MSB = 1
const ADC_SARADC_DTEST_RTC_ADDR_LSB = 0
const ADC_SARADC_ENT_TSENS_ADDR = 0x7
const ADC_SARADC_ENT_TSENS_ADDR_MSB = 2
const ADC_SARADC_ENT_TSENS_ADDR_LSB = 2
const ADC_SARADC_ENT_RTC_ADDR = 0x7
const ADC_SARADC_ENT_RTC_ADDR_MSB = 3
const ADC_SARADC_ENT_RTC_ADDR_LSB = 3
const ADC_SARADC_ENCAL_REF_ADDR = 0x7
const ADC_SARADC_ENCAL_REF_ADDR_MSB = 4
const ADC_SARADC_ENCAL_REF_ADDR_LSB = 4
const I2C_SARADC_TSENS_DAC = 0x6
const I2C_SARADC_TSENS_DAC_MSB = 3
const I2C_SARADC_TSENS_DAC_LSB = 0
