package freertos

import _ "unsafe"

const I2C_DIG_REG = 0x6D
const I2C_DIG_REG_HOSTID = 1
const I2C_DIG_REG_EXT_RTC_DREG = 4
const I2C_DIG_REG_EXT_RTC_DREG_MSB = 4
const I2C_DIG_REG_EXT_RTC_DREG_LSB = 0
const I2C_DIG_REG_ENX_RTC_DREG = 4
const I2C_DIG_REG_ENX_RTC_DREG_MSB = 7
const I2C_DIG_REG_ENX_RTC_DREG_LSB = 7
const I2C_DIG_REG_EXT_RTC_DREG_SLEEP = 5
const I2C_DIG_REG_EXT_RTC_DREG_SLEEP_MSB = 4
const I2C_DIG_REG_EXT_RTC_DREG_SLEEP_LSB = 0
const I2C_DIG_REG_ENX_RTC_DREG_SLEEP = 5
const I2C_DIG_REG_ENX_RTC_DREG_SLEEP_MSB = 7
const I2C_DIG_REG_ENX_RTC_DREG_SLEEP_LSB = 7
const I2C_DIG_REG_EXT_DIG_DREG = 6
const I2C_DIG_REG_EXT_DIG_DREG_MSB = 4
const I2C_DIG_REG_EXT_DIG_DREG_LSB = 0
const I2C_DIG_REG_ENX_DIG_DREG = 6
const I2C_DIG_REG_ENX_DIG_DREG_MSB = 7
const I2C_DIG_REG_ENX_DIG_DREG_LSB = 7
const I2C_DIG_REG_EXT_DIG_DREG_SLEEP = 7
const I2C_DIG_REG_EXT_DIG_DREG_SLEEP_MSB = 4
const I2C_DIG_REG_EXT_DIG_DREG_SLEEP_LSB = 0
const I2C_DIG_REG_ENX_DIG_DREG_SLEEP = 7
const I2C_DIG_REG_ENX_DIG_DREG_SLEEP_MSB = 7
const I2C_DIG_REG_ENX_DIG_DREG_SLEEP_LSB = 7
const I2C_DIG_REG_OR_EN_CONT_CAL = 9
const I2C_DIG_REG_OR_EN_CONT_CAL_MSB = 7
const I2C_DIG_REG_OR_EN_CONT_CAL_LSB = 7
const I2C_DIG_REG_XPD_RTC_REG = 13
const I2C_DIG_REG_XPD_RTC_REG_MSB = 2
const I2C_DIG_REG_XPD_RTC_REG_LSB = 2
const I2C_DIG_REG_XPD_DIG_REG = 13
const I2C_DIG_REG_XPD_DIG_REG_MSB = 3
const I2C_DIG_REG_XPD_DIG_REG_LSB = 3
