package freertos

import _ "unsafe"

const RTCIO_GPIO0_CHANNEL = 0
const RTCIO_CHANNEL_0_GPIO_NUM = 0
const RTCIO_GPIO1_CHANNEL = 1
const RTCIO_CHANNEL_1_GPIO_NUM = 1
const RTCIO_GPIO2_CHANNEL = 2
const RTCIO_CHANNEL_2_GPIO_NUM = 2
const RTCIO_GPIO3_CHANNEL = 3
const RTCIO_CHANNEL_3_GPIO_NUM = 3
const RTCIO_GPIO4_CHANNEL = 4
const RTCIO_CHANNEL_4_GPIO_NUM = 4
const RTCIO_GPIO5_CHANNEL = 5
const RTCIO_CHANNEL_5_GPIO_NUM = 5
const RTCIO_GPIO6_CHANNEL = 6
const RTCIO_CHANNEL_6_GPIO_NUM = 6
const RTCIO_GPIO7_CHANNEL = 7
const RTCIO_CHANNEL_7_GPIO_NUM = 7
const RTCIO_GPIO8_CHANNEL = 8
const RTCIO_CHANNEL_8_GPIO_NUM = 8
const RTCIO_GPIO9_CHANNEL = 9
const RTCIO_CHANNEL_9_GPIO_NUM = 9
const RTCIO_GPIO10_CHANNEL = 10
const RTCIO_CHANNEL_10_GPIO_NUM = 10
const RTCIO_GPIO11_CHANNEL = 11
const RTCIO_CHANNEL_11_GPIO_NUM = 11
const RTCIO_GPIO12_CHANNEL = 12
const RTCIO_CHANNEL_12_GPIO_NUM = 12
const RTCIO_GPIO13_CHANNEL = 13
const RTCIO_CHANNEL_13_GPIO_NUM = 13
const RTCIO_GPIO14_CHANNEL = 14
const RTCIO_CHANNEL_14_GPIO_NUM = 14
const RTCIO_GPIO15_CHANNEL = 15
const RTCIO_CHANNEL_15_GPIO_NUM = 15
const RTCIO_GPIO16_CHANNEL = 16
const RTCIO_CHANNEL_16_GPIO_NUM = 16
const RTCIO_GPIO17_CHANNEL = 17
const RTCIO_CHANNEL_17_GPIO_NUM = 17
const RTCIO_GPIO18_CHANNEL = 18
const RTCIO_CHANNEL_18_GPIO_NUM = 18
const RTCIO_GPIO19_CHANNEL = 19
const RTCIO_CHANNEL_19_GPIO_NUM = 19
const RTCIO_GPIO20_CHANNEL = 20
const RTCIO_CHANNEL_20_GPIO_NUM = 20
const RTCIO_GPIO21_CHANNEL = 21
const RTCIO_CHANNEL_21_GPIO_NUM = 21
