package freertos

import _ "unsafe"

const RWDT_LL_WDT_WKEY_VALUE = 0x50D83AA1
const RWDT_LL_STG_SEL_OFF = 0
const RWDT_LL_STG_SEL_INT = 1
const RWDT_LL_STG_SEL_RESET_CPU = 2
const RWDT_LL_STG_SEL_RESET_SYSTEM = 3
const RWDT_LL_STG_SEL_RESET_RTC = 4
const RWDT_LL_RESET_LENGTH_100_NS = 0
const RWDT_LL_RESET_LENGTH_200_NS = 1
const RWDT_LL_RESET_LENGTH_300_NS = 2
const RWDT_LL_RESET_LENGTH_400_NS = 3
const RWDT_LL_RESET_LENGTH_500_NS = 4
const RWDT_LL_RESET_LENGTH_800_NS = 5
const RWDT_LL_RESET_LENGTH_1600_NS = 6
const RWDT_LL_RESET_LENGTH_3200_NS = 7

type RwdtDevT RtcCntlDevT
