package freertos

import _ "unsafe"

const MSPI_FUNC_NUM = 0
const MSPI_IOMUX_PIN_NUM_CS1 = 26
const MSPI_IOMUX_PIN_NUM_HD = 27
const MSPI_IOMUX_PIN_NUM_WP = 28
const MSPI_IOMUX_PIN_NUM_CS0 = 29
const MSPI_IOMUX_PIN_NUM_CLK = 30
const MSPI_IOMUX_PIN_NUM_MISO = 31
const MSPI_IOMUX_PIN_NUM_MOSI = 32
const MSPI_IOMUX_PIN_NUM_D4 = 33
const MSPI_IOMUX_PIN_NUM_D5 = 34
const MSPI_IOMUX_PIN_NUM_D6 = 35
const MSPI_IOMUX_PIN_NUM_D7 = 36
const MSPI_IOMUX_PIN_NUM_DQS = 37
const SPI2_FUNC_NUM = 4
const SPI2_IOMUX_PIN_NUM_HD = 9
const SPI2_IOMUX_PIN_NUM_CS = 10
const SPI2_IOMUX_PIN_NUM_MOSI = 11
const SPI2_IOMUX_PIN_NUM_CLK = 12
const SPI2_IOMUX_PIN_NUM_MISO = 13
const SPI2_IOMUX_PIN_NUM_WP = 14
const SPI2_FUNC_NUM_OCT = 2
const SPI2_IOMUX_PIN_NUM_HD_OCT = 33
const SPI2_IOMUX_PIN_NUM_CS_OCT = 34
const SPI2_IOMUX_PIN_NUM_MOSI_OCT = 35
const SPI2_IOMUX_PIN_NUM_CLK_OCT = 36
const SPI2_IOMUX_PIN_NUM_MISO_OCT = 37
const SPI2_IOMUX_PIN_NUM_WP_OCT = 38
const SPI2_IOMUX_PIN_NUM_IO4_OCT = 10
const SPI2_IOMUX_PIN_NUM_IO5_OCT = 11
const SPI2_IOMUX_PIN_NUM_IO6_OCT = 12
const SPI2_IOMUX_PIN_NUM_IO7_OCT = 13
