package freertos

import _ "unsafe"

const TOUCH_PAD_NUM1_GPIO_NUM = 1
const TOUCH_PAD_NUM2_GPIO_NUM = 2
const TOUCH_PAD_NUM3_GPIO_NUM = 3
const TOUCH_PAD_NUM4_GPIO_NUM = 4
const TOUCH_PAD_NUM5_GPIO_NUM = 5
const TOUCH_PAD_NUM6_GPIO_NUM = 6
const TOUCH_PAD_NUM7_GPIO_NUM = 7
const TOUCH_PAD_NUM8_GPIO_NUM = 8
const TOUCH_PAD_NUM9_GPIO_NUM = 9
const TOUCH_PAD_NUM10_GPIO_NUM = 10
const TOUCH_PAD_NUM11_GPIO_NUM = 11
const TOUCH_PAD_NUM12_GPIO_NUM = 12
const TOUCH_PAD_NUM13_GPIO_NUM = 13
const TOUCH_PAD_NUM14_GPIO_NUM = 14
