package freertos

import _ "unsafe"

const UART_NUM_0_TXD_DIRECT_GPIO_NUM = 43
const UART_NUM_0_RXD_DIRECT_GPIO_NUM = 44
const UART_NUM_0_CTS_DIRECT_GPIO_NUM = 16
const UART_NUM_0_RTS_DIRECT_GPIO_NUM = 15
const UART_NUM_1_TXD_DIRECT_GPIO_NUM = 17
const UART_NUM_1_RXD_DIRECT_GPIO_NUM = 18
const UART_NUM_1_CTS_DIRECT_GPIO_NUM = 20
const UART_NUM_1_RTS_DIRECT_GPIO_NUM = 19
