package freertos

import _ "unsafe"

const ERI_DEBUG_OFFSET = 0x100000
const TRAXCTRL_SMPER_SHIFT = 12
const TRAXCTRL_SMPER_MASK = 0x7
const TRAXCTRL_ATID_MASK = 0x7F
const TRAXCTRL_ATID_SHIFT = 24
const TRAXSTAT_MEMSZ_SHIFT = 8
const TRAXSTAT_MEMSZ_MASK = 0x1F
const TRAXADDR_TADDR_SHIFT = 0
const TRAXADDR_TADDR_MASK = 0x1FFFFF
const TRAXADDR_TWRAP_SHIFT = 21
const TRAXADDR_TWRAP_MASK = 0x3FF
const PCMATCHCTRL_PCML_SHIFT = 0
const PCMATCHCTRL_PCML_MASK = 0x1F
const PMCTRL_KRNLCNT_SHIFT = 3
const PMCTRL_TRACELEVEL_SHIFT = 4
const PMCTRL_TRACELEVEL_MASK = 0xf
const PMCTRL_SELECT_SHIFT = 8
const PMCTRL_SELECT_MASK = 0x1f
const PMCTRL_MASK_SHIFT = 16
const PMCTRL_MASK_MASK = 0xffff
