name: Clean unused branch

on:
  issues:
    types: [closed]

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: Skip Cache Parser Tool
        run: |
          go env -w GOPRIVATE=github.com/MeteorsLiu/llpkgstore
      - name: Set up Parser Tool
        run: |
          go install -v github.com/MeteorsLiu/llpkgstore/cmd/llpkgstore@rebase
      - name: Run cleaner process
        run: |
          llpkgstore cleaner