name: Legacy version maintenance


# label trigger
on:
  label:
    types: [created]



jobs:
  maintenance:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.label.name, 'branch:release-branch.')
    steps:
      - name: Checkout to website
        uses: actions/checkout@v4
        with:
          ref: website
          path: .website
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          path: .main
      # actions/checkout cannot fetch tags even though using fetch-tags
      # see issue: https://github.com/actions/checkout/issues/1471
      - name: Fetch all tags
        working-directory: .main
        run: |
          git fetch --all --tags --prune

      - name: Copy llpkgstore.json to root
        continue-on-error: true
        run: |
          # ignore error
          ls .website .website/public
          cp .website/public/llpkgstore.json .main
          rm -rf .website

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: Set up Parser Tool
        run: |
          go install -v github.com/goplus/llpkgstore/cmd/maintain@latest
      - name: Run maintenance process
        working-directory: .main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          maintain labelcreate -l "${{ github.event.label.name }}"