name: Copy llpkgstore.json to gh-pages

on:
    push:
        branches:
            - main
        paths:
            - '/_website/public/llpkgstore.json'

permissions:
    contents: write

jobs:
    copy-file:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout main branch
              uses: actions/checkout@v3
              with:
                  ref: main

            - name: Copy llpkgstore.json to root
              run: |
                  cp _website/public/llpkgstore.json .

            - name: Checkout gh-pages branch
              uses: actions/checkout@v3
              with:
                  ref: gh-pages
                  path: gh-pages

            - name: Move llpkgstore.json to gh-pages root
              run: |
                  mv llpkgstore.json gh-pages/

            - name: Commit and push changes
              working-directory: gh-pages
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add llpkgstore.json
                  git commit -m "Update llpkgstore.json" || true
                  git push
